### ISSUE TITLE
게시판 한글 입력 오류

### ISSUE THREAD

**Issue by kingesay** [Bue-von-hon/alphabet#16]
1. 내용이나 제목에 한글입력시 오류
2. 뮤에 받침추가시 일정단어 투명

**Comment by Bue-von-hon** [comment]
한글 입력 오류는 db설정 문제
아마존 콘솔에서 문자열 설정을 바꿔도 실제 db에서는 변하지 않는 몇가지 속성들이 있었음
해당 속성값을 직접 db에 접속해서 변경하고 이미 만들어둔 테이블에도 적용하니 문제 해결
