### ISSUE TITLE
소개화면 크기가 너무 작음

### ISSUE THREAD

**Issue by Bue-von-hon** [Bue-von-hon/alphabet#27]
소개 페이지에서 텍스트 공간의 넓이가 너무 좁음

**Comment by kingesay** [comment]
무엇을 했을 때 어떻게 되는지 알고 싶습니다.

**Comment by Bue-von-hon** [comment]
소개화면에 텍스트가 한 줄에 다 나오는것이 아니라 짤려서 보임
다른곳에서도 마찬가지로 넓이가 너무 좁음
